import AppKit
import Foundation
import Observation
import VibeApplication

/// The library of avatars as the screens see it (#154): the avatars kept and the drafts not yet
/// kept, the one selected, the one the floating panel shows, and what is being made — generated by
/// an agent, redrawn one expression at a time, imported from an archive.
///
/// Held by the application's model, not by the Settings window: closing the window does not stop
/// a generation, and what it brings back is written as a draft even with no window open. The
/// library is the only truth: every change goes through it, then the model reads it again.
@MainActor
@Observable
public final class AvatarLibraryModel {
  /// What the screen says went wrong.
  public enum Problem: Equatable, Sendable {
    case generation(AvatarGenerationError)
    case archive(AvatarProblem)
    /// The avatar in use cannot be read, or lacks expressions: the default one is shown.
    case storedAvatar(missing: [AvatarExpression])
    /// `AvatarLibraryRules.maximumCount` avatars already: nothing new is made.
    case limitReached
    /// The library refused or failed a change: it is as it was.
    case saving
    case exporting
  }

  /// What a generation draws.
  public enum Work: Equatable, Sendable {
    case wholeSet
    case expression(AvatarExpression)
  }

  /// A generation, under way or failed. One under way is the only one; one that failed stays
  /// listed for the run, to try again or remove — never written.
  public struct Job: Identifiable, Equatable, Sendable {
    public enum Phase: Equatable, Sendable {
      case running
      case failed(AvatarGenerationError, at: Date)
    }

    /// Where what it brings back goes.
    public enum Destination: Equatable, Sendable {
      /// A new draft; based on the kept avatar it redraws, if any.
      case newDraft(basedOn: AvatarID?)
      /// A draft, whose images it replaces.
      case draft(AvatarID)
    }

    public let id: UUID
    public let kind: Work
    public let destination: Destination
    /// What the user described: a failed generation is tried again, or edited, from it.
    public let description: String
    public let provider: AgentProviderID
    public let startedAt: Date
    public var phase: Phase
    /// The avatar selected when it started, if it redraws one: the kept avatar whose draft it
    /// changes. Still selected at the end, the selection goes to what it wrote.
    public var origin: AvatarID?

    /// The avatar it redraws, when it redraws one rather than making a new avatar.
    public var avatar: AvatarID? {
      switch destination {
      case .newDraft(let basedOn): return kind == .wholeSet ? nil : basedOn
      case .draft(let id): return id
      }
    }
  }

  /// What the list selects: an avatar of the library, or a generation that is not one yet.
  public enum Selection: Hashable, Sendable {
    case avatar(AvatarID)
    case job(UUID)
  }

  // MARK: - State

  /// The default avatar first, then the others in the order they entered the library.
  public private(set) var entries: [AvatarLibraryEntry] = []
  /// The avatar the floating panel shows.
  public private(set) var inUse: AvatarID = .default
  /// Its images: those of the default avatar while the one in use cannot be used.
  public private(set) var inUseImages: [AvatarExpression: NSImage] = [:]
  /// Why the avatar in use is not shown, when it is not.
  public private(set) var inUseProblem: Problem?
  /// Whether a new avatar can be made — generated, imported or copied — or the library is full.
  public private(set) var canCreate = true

  public private(set) var selection: Selection?
  /// The selected avatar's images, possibly incomplete; `nil` while none is selected, or when it
  /// cannot be read.
  public private(set) var selectedAvatar: AvatarSpriteSet?
  public private(set) var selectedImages: [AvatarExpression: NSImage] = [:]

  /// Whether keeping a draft also puts it in the floating panel: checked by default.
  public var usesKeptDraft = true
  /// Files of the last archive read that are no avatar's, and the draft it became.
  public private(set) var ignoredFiles: (draft: AvatarID, count: Int)?

  public var description = ""
  public var selectedProvider: AgentProviderID?
  public private(set) var options: [AvatarGeneratorOption] = []

  /// The generations under way — one at most — and those that failed during this run.
  public private(set) var jobs: [Job] = []
  /// An archive being read.
  public private(set) var isImporting = false
  public private(set) var problem: Problem?
  /// Changed once a generation or an import finished, for VoiceOver and for whoever looks.
  public private(set) var lastEvent: UUID?

  @ObservationIgnored private let workshop: AvatarWorkshop
  @ObservationIgnored private let library: any AvatarLibrary
  @ObservationIgnored private let generators: (any AvatarGeneratorResolving)?
  @ObservationIgnored private let now: @Sendable () -> Date
  /// The generation under way, until what it brought back is written: the tests wait for it
  /// rather than for a length of time.
  @ObservationIgnored private(set) var task: Task<Void, Never>?
  /// The generation whose result counts. One cancelled may still end — in any way, cancelled in
  /// the middle of launching its process — and must then change nothing.
  @ObservationIgnored private var currentRun: UUID?
  /// The generation `task` runs: one that ends leaves the task of a later one alone.
  @ObservationIgnored private var taskRun: UUID?

  public init(
    workshop: AvatarWorkshop, library: any AvatarLibrary,
    generators: (any AvatarGeneratorResolving)?,
    now: @escaping @Sendable () -> Date = Date.init
  ) {
    self.workshop = workshop
    self.library = library
    self.generators = generators
    self.now = now
  }

  // MARK: - Reading

  /// Reads the library: its avatars, the one in use and its images. Selects, the first time, the
  /// latest draft — made before the application was quit — or the avatar in use.
  public func load() async {
    await refresh()
    if selection == nil {
      let draft = entries.last { $0.isDraft }
      await select(.avatar(draft?.id ?? inUse))
    }
  }

  /// Reads the library again, after a change, or when the screen comes back.
  public func refresh() async {
    // A library that cannot be read now — held by another instance — is shown as last read.
    if let entries = try? await library.entries(), let inUse = try? await library.inUse() {
      self.entries = entries
      self.inUse = inUse
      canCreate = (try? await library.canCreate()) ?? canCreate
    }
    await loadInUseImages()
    await reloadSelection()
  }

  /// The images the floating panel shows: those of the avatar in use, or of the default one while
  /// it cannot be used.
  private func loadInUseImages() async {
    let id = inUse
    var shown: AvatarSpriteSet?
    var problem: Problem?
    if id != .default {
      do {
        let avatar = try await library.load(id)
        if avatar.isComplete {
          shown = avatar
        } else {
          problem = .storedAvatar(missing: avatar.missingExpressions)
        }
      } catch {
        problem = .storedAvatar(missing: [])
      }
    }
    if shown == nil { shown = try? await library.load(.default) }
    // Another avatar put in use meanwhile: its own reading counts.
    guard id == inUse else { return }
    inUseProblem = problem
    inUseImages = Self.images(of: shown)
  }

  /// The entry of `id`, as last read.
  public func entry(_ id: AvatarID) -> AvatarLibraryEntry? {
    entries.first { $0.id == id }
  }

  public func job(_ id: UUID) -> Job? {
    jobs.first { $0.id == id }
  }

  /// The generation under way.
  public var work: Job? {
    jobs.first { $0.phase == .running }
  }

  /// The generations that failed during this run.
  public var failures: [Job] {
    jobs.filter { $0.phase != .running }
  }

  /// The avatar selected, when it is one of the library.
  public var selectedID: AvatarID? {
    guard case .avatar(let id) = selection else { return nil }
    return id
  }

  public var selectedEntry: AvatarLibraryEntry? {
    selectedID.flatMap(entry)
  }

  /// What the user calls an avatar: the default one's name in their language, or the one it
  /// was given.
  public static func name(of entry: AvatarLibraryEntry) -> String {
    if entry.id == .default { return AvatarLibraryRules.defaultAvatarName }
    let name = entry.manifest?.name ?? ""
    return name.isEmpty ? importedName : name
  }

  private static var importedName: String {
    String(
      localized: LocalizedStringResource(
        "Imported avatar", bundle: .module,
        comment: "The name of an avatar read from an archive."))
  }

  // MARK: - Selecting

  /// Shows an avatar, or a generation, in the preview. It does not change the one in use.
  public func select(_ selection: Selection?) async {
    self.selection = selection
    await reloadSelection()
  }

  /// Reads the selected avatar again. One no longer there gives its place to the avatar in use.
  private func reloadSelection() async {
    let fallback: Selection? = entries.isEmpty ? nil : .avatar(inUse)
    switch selection {
    case .avatar(let id) where entry(id) == nil: selection = fallback
    case .job(let id) where job(id) == nil: selection = fallback
    default: break
    }
    guard case .avatar(let id) = selection else {
      setSelected(nil)
      return
    }
    let requested = selection
    let avatar = try? await library.load(id)
    // Another selection meanwhile: its own reading counts.
    guard selection == requested else { return }
    setSelected(avatar)
  }

  // MARK: - Agents

  /// Which agents can draw now. Asked when the screen opens.
  public func refreshOptions() async {
    guard let generators else { return }
    options = await generators.options()
    if selectedProvider == nil || !options.contains(where: { $0.id == selectedProvider }) {
      selectedProvider = options.first { $0.unavailability == nil }?.id
    }
  }

  public var selectedGenerator: (any AvatarGenerating)? {
    generator(for: selectedProvider)
  }

  private func generator(for provider: AgentProviderID?) -> (any AvatarGenerating)? {
    options.first { $0.id == provider && $0.unavailability == nil }?.generator
  }

  /// Whether nothing is being made: one generation, or one import, at a time.
  public var isIdle: Bool { work == nil && !isImporting }

  /// Whether a new avatar can be started now — generated or imported: the card that makes one is
  /// greyed otherwise.
  public var canStartCreation: Bool { isIdle && canCreate }

  public var canGenerate: Bool {
    canStartCreation && selectedGenerator != nil
      && !AvatarPrompt.sanitizedDescription(description).isEmpty
  }

  // MARK: - Making

  /// Draws a new avatar from the description, in the background. What comes back is written as a
  /// draft, selected; the description is emptied.
  public func generate() {
    guard canGenerate, let generator = selectedGenerator, let provider = selectedProvider else {
      return
    }
    let description = description
    self.description = ""
    start(
      Job(
        id: UUID(), kind: .wholeSet, destination: .newDraft(basedOn: nil),
        description: description, provider: provider, startedAt: now(), phase: .running),
      with: generator)
  }

  /// Starts a failed generation again, from the same description: with the same agent, or the one
  /// selected when that one can no longer draw.
  public func retry(_ id: UUID) {
    guard let failed = job(id), failed.phase != .running, canStartCreation else { return }
    let provider = generator(for: failed.provider) != nil ? failed.provider : selectedProvider
    guard let provider, let generator = generator(for: provider) else { return }
    jobs.removeAll { $0.id == id }
    start(
      Job(
        id: UUID(), kind: .wholeSet, destination: .newDraft(basedOn: nil),
        description: failed.description, provider: provider, startedAt: now(), phase: .running),
      with: generator)
  }

  /// Removes a failed generation from the list.
  public func dismiss(_ id: UUID) async {
    guard job(id)?.phase != .running else { return }
    jobs.removeAll { $0.id == id }
    await reloadSelection()
  }

  /// Takes the description of a failed generation back, to change it, and removes it.
  public func reviseDescription(of id: UUID) async {
    guard let failed = job(id), failed.phase != .running else { return }
    description = failed.description
    await dismiss(id)
  }

  /// Whether an expression of the selected avatar can be drawn again: a draft, or a kept avatar
  /// that says what it looks like — or lacks expressions. Not the default one.
  public var canRegenerate: Bool {
    guard isIdle, selectedGenerator != nil, let entry = selectedEntry, entry.id != .default,
      entry.problem != .unreadable, selectedAvatar != nil
    else { return false }
    if entry.isDraft { return true }
    if case .incomplete = entry.problem { return true }
    return !(entry.manifest?.description ?? "").isEmpty
  }

  /// Draws one expression of the selected avatar again. A draft changes where it is; a kept avatar
  /// does not: the draft that redraws it does — made now, or the one already there — and replaces
  /// it once kept.
  public func regenerate(_ expression: AvatarExpression) {
    guard canRegenerate, let generator = selectedGenerator, let provider = selectedProvider,
      let entry = selectedEntry, let selected = selectedAvatar
    else { return }
    let destination: Job.Destination
    let base: AvatarSpriteSet?
    if entry.isDraft {
      destination = .draft(entry.id)
      base = selected
    } else if let draft = entries.first(where: { $0.state == .draft(basedOn: entry.id) }) {
      destination = .draft(draft.id)
      base = nil
    } else {
      destination = .newDraft(basedOn: entry.id)
      base = selected
    }
    let library = library
    let job = Job(
      id: UUID(), kind: .expression(expression), destination: destination,
      description: entry.manifest?.description ?? "", provider: provider, startedAt: now(),
      phase: .running, origin: entry.id)
    run(job) { workshop in
      let avatar: AvatarSpriteSet
      if let base {
        avatar = base
      } else if case .draft(let draft) = destination {
        avatar = try await library.load(draft)
      } else {
        throw AvatarGenerationError.failed("no base")
      }
      return try await workshop.regenerate(expression, in: avatar, with: generator)
    }
  }

  /// Draws the whole of a draft again, from its description, under its name.
  public func regenerateAll(_ id: AvatarID) {
    guard isIdle, let entry = entry(id), entry.isDraft,
      let description = entry.manifest?.description, !description.isEmpty,
      let generator = selectedGenerator, let provider = selectedProvider
    else { return }
    let name = entry.manifest?.name ?? ""
    let job = Job(
      id: UUID(), kind: .wholeSet, destination: .draft(id), description: description,
      provider: provider, startedAt: now(), phase: .running, origin: id)
    run(job) { workshop in
      var avatar = try await workshop.generate(
        description: description, name: name, provider: provider, with: generator)
      if !name.isEmpty { avatar.manifest.name = name }
      return avatar
    }
  }

  private func start(_ job: Job, with generator: any AvatarGenerating) {
    let description = job.description
    let provider = job.provider
    run(job) { workshop in
      try await workshop.generate(
        description: description, name: "", provider: provider, with: generator)
    }
    selection = .job(job.id)
    setSelected(nil)
  }

  /// Stops the generation under way: its process is stopped, nothing is written.
  public func cancel() {
    guard let work else { return }
    currentRun = nil
    task?.cancel()
    task = nil
    jobs.removeAll { $0.id == work.id }
    if selection == .job(work.id) {
      selection = .avatar(inUse)
      Task { await self.reloadSelection() }
    }
  }

  private func run(
    _ job: Job, _ body: @escaping @Sendable (AvatarWorkshop) async throws -> AvatarSpriteSet
  ) {
    problem = nil
    jobs.append(job)
    let workshop = workshop
    let run = UUID()
    currentRun = run
    taskRun = run
    task = Task { [weak self] in
      do {
        let result = try await body(workshop)
        await self?.finish(job, with: result, run: run)
      } catch let error as AvatarGenerationError {
        await self?.fail(job, error, run: run)
      } catch {
        await self?.fail(job, .failed("unexpected"), run: run)
      }
    }
  }

  /// Writes what came back as a draft, at once — beyond the limit too: what was made is never
  /// lost — then selects it.
  private func finish(_ job: Job, with avatar: AvatarSpriteSet, run: UUID) async {
    guard currentRun == run else { return }
    // From here, what came back is written: cancelling no longer throws it away.
    currentRun = nil
    let written: AvatarID?
    do {
      switch job.destination {
      case .newDraft(let basedOn):
        written = try await library.saveDraft(avatar, basedOn: basedOn)
      case .draft(let id):
        try await library.updateDraft(id, with: avatar)
        written = id
      }
    } catch {
      written = nil
    }
    // The generation's line gives its place to the draft; a redrawing takes the eye to its draft.
    let follows =
      selection == .job(job.id) || written.map { selection == .avatar($0) } == true
      || job.origin.map { selection == .avatar($0) } == true
    jobs.removeAll { $0.id == job.id }
    if taskRun == run { task = nil }
    await refresh()
    guard let written else {
      problem = .saving
      lastEvent = UUID()
      Announcer.announce(AvatarPresentation.message(for: .saving))
      return
    }
    if follows { await select(.avatar(written)) }
    lastEvent = UUID()
    Announcer.announce(
      avatar.isComplete
        ? LocalizedStringResource(
          "The avatar is ready: check it, then keep it.", bundle: .module,
          comment: "Said when a generated avatar can be previewed.")
        : LocalizedStringResource(
          "The avatar is ready, with expressions still missing.", bundle: .module,
          comment: "Said when an incomplete avatar can be previewed."))
  }

  private func fail(_ job: Job, _ error: AvatarGenerationError, run: UUID) async {
    guard currentRun == run else { return }
    currentRun = nil
    if taskRun == run { task = nil }
    if job.kind == .wholeSet, job.destination == .newDraft(basedOn: nil),
      let index = jobs.firstIndex(where: { $0.id == job.id })
    {
      // A new avatar that failed stays listed, to try again or remove.
      jobs[index].phase = .failed(error, at: now())
    } else {
      // A redrawing leaves its avatar as it was, and says why.
      jobs.removeAll { $0.id == job.id }
      problem = .generation(error)
    }
    lastEvent = UUID()
    Announcer.announce(AvatarPresentation.message(for: .generation(error)))
  }

  // MARK: - Archives

  /// Reads an archive, off the main actor, and writes what it holds as a draft — never over an
  /// avatar. Nothing is read while a generation runs, nor when the library is full.
  public func importArchive(_ data: Data) async {
    guard isIdle else { return }
    guard canCreate else {
      problem = .limitReached
      return
    }
    problem = nil
    isImporting = true
    defer { isImporting = false }
    let workshop = workshop
    do {
      var (avatar, ignored) = try await Task.detached(priority: .userInitiated) {
        try workshop.importArchive(data)
      }.value
      if avatar.manifest.name.isEmpty { avatar.manifest.name = Self.importedName }
      let draft: AvatarID
      do {
        draft = try await library.saveDraft(avatar, basedOn: nil)
      } catch {
        problem = .saving
        return
      }
      ignoredFiles = ignored > 0 ? (draft, ignored) : nil
      await refresh()
      await select(.avatar(draft))
      lastEvent = UUID()
    } catch let problem as AvatarProblem {
      self.problem = .archive(problem)
    } catch {
      problem = .archive(.archiveUnreadable)
    }
  }

  /// An archive refused before it was read: too large to be one, or the library full.
  public func reject(_ problem: AvatarProblem) {
    self.problem = .archive(problem)
  }

  /// The archive of an avatar — the default one included — with or without its description.
  public func exportArchive(_ id: AvatarID, includingDescription: Bool) async -> Data? {
    do {
      let avatar = try await library.load(id)
      return try workshop.exportArchive(avatar, includingDescription: includingDescription)
    } catch {
      problem = .exporting
      return nil
    }
  }

  /// The name an exported archive is given: `Avatar - <name>`.
  public func exportFileName(_ id: AvatarID) -> String {
    let name = entry(id).map(Self.name) ?? ""
    let cleaned = name.components(separatedBy: CharacterSet(charactersIn: "/:\\")).joined(
      separator: "-")
    return cleaned.isEmpty ? "Avatar" : "Avatar - \(cleaned)"
  }

  // MARK: - Deciding

  /// Whether a draft can be kept: complete, and not being redrawn.
  public func canKeep(_ id: AvatarID) -> Bool {
    guard let entry = entry(id), entry.isDraft, work?.avatar != id else { return false }
    return selectedID == id ? selectedAvatar?.isComplete == true : true
  }

  /// Keeps a draft — and uses it, when `usesKeptDraft` says so. A draft that redraws a kept
  /// avatar replaces it, which keeps its place and its use.
  public func keep(_ id: AvatarID) async {
    guard canKeep(id) else { return }
    let uses = usesKeptDraft
    do {
      let kept = try await library.keep(id)
      if uses { try await library.setInUse(kept) }
      problem = nil
      if ignoredFiles?.draft == id { ignoredFiles = nil }
      await refresh()
      await select(.avatar(kept))
    } catch {
      problem = Self.problem(for: error)
      await refresh()
    }
  }

  /// Throws a draft away: what redraws it stops first.
  public func discard(_ id: AvatarID) async {
    guard entry(id)?.isDraft == true else { return }
    await remove(id)
  }

  /// The avatar the floating panel shows: a kept one, complete, or the default one.
  public func use(_ id: AvatarID) async {
    await change { try await $0.setInUse(id) }
  }

  public func rename(_ id: AvatarID, to name: String) async {
    await change { try await $0.rename(id, to: name) }
  }

  /// A kept copy, selected.
  public func duplicate(_ id: AvatarID) async {
    do {
      let copy = try await library.duplicate(id)
      problem = nil
      await refresh()
      await select(.avatar(copy))
    } catch {
      problem = Self.problem(for: error)
      await refresh()
    }
  }

  /// Deletes an avatar or discards a draft; what redraws it stops first. The one in use gives its
  /// place to the default one, in the panel at once.
  public func remove(_ id: AvatarID) async {
    if work?.avatar == id { cancel() }
    await change { try await $0.remove(id) }
    if ignoredFiles?.draft == id { ignoredFiles = nil }
  }

  /// A draft to complete a kept avatar that lacks expressions — the one already made, if any —
  /// selected.
  public func completeDraft(of id: AvatarID) async {
    do {
      let draft = try await library.draftToComplete(id)
      problem = nil
      await refresh()
      await select(.avatar(draft))
    } catch {
      problem = Self.problem(for: error)
      await refresh()
    }
  }

  private func change(_ body: (any AvatarLibrary) async throws -> Void) async {
    do {
      try await body(library)
      problem = nil
    } catch {
      problem = Self.problem(for: error)
    }
    await refresh()
  }

  private static func problem(for error: any Error) -> Problem {
    if case AvatarLibraryError.limitReached = error { return .limitReached }
    return .saving
  }

  // MARK: - Images

  private func setSelected(_ avatar: AvatarSpriteSet?) {
    selectedAvatar = avatar
    selectedImages = Self.images(of: avatar)
  }

  static func images(of avatar: AvatarSpriteSet?) -> [AvatarExpression: NSImage] {
    guard let avatar else { return [:] }
    var images: [AvatarExpression: NSImage] = [:]
    for (expression, data) in avatar.sprites {
      images[expression] = NSImage(data: data)
    }
    return images
  }
}
