import AppKit
import Foundation
import Observation
import VibeApplication

/// The avatar in use, and the one being made (#41): generated by an agent, redrawn one expression
/// at a time, imported from an archive; accepted, discarded, exported, or put back to the default.
///
/// Held by the application's model, not by the Settings window: closing the window does not stop
/// a generation. Whatever is made is a candidate; the avatar in use changes only when it is
/// accepted.
@MainActor
@Observable
public final class AvatarStudioModel {
  /// What the screen says went wrong.
  public enum Problem: Equatable, Sendable {
    case generation(AvatarGenerationError)
    case archive(AvatarProblem)
    /// The kept avatar cannot be read, or lacks expressions: the default one is shown.
    case storedAvatar(missing: [AvatarExpression])
    case saving
    case exporting
  }

  /// What a generation under way draws.
  public enum Work: Equatable, Sendable {
    case wholeSet
    case expression(AvatarExpression)
  }

  // MARK: - State

  /// The avatar the panel shows: the one kept, or the default one.
  public private(set) var current: AvatarSpriteSet?
  /// Whether `current` is the user's rather than the default one.
  public private(set) var isCustom = false
  public private(set) var currentImages: [AvatarExpression: NSImage] = [:]
  /// The avatar being made, until it is accepted or discarded.
  public private(set) var candidate: AvatarSpriteSet?
  public private(set) var candidateImages: [AvatarExpression: NSImage] = [:]
  /// Files of the last archive read that are no avatar's.
  public private(set) var ignoredFiles = 0

  public var description = ""
  public var selectedProvider: AgentProviderID?
  public private(set) var options: [AvatarGeneratorOption] = []

  /// What is being generated, and since when.
  public private(set) var work: (kind: Work, startedAt: Date)?
  public private(set) var problem: Problem?
  /// Said once a generation or an import finished, for VoiceOver and for whoever looks.
  public private(set) var lastEvent: UUID?

  @ObservationIgnored private let workshop: AvatarWorkshop
  @ObservationIgnored private let store: any AvatarStore
  @ObservationIgnored private let generators: (any AvatarGeneratorResolving)?
  @ObservationIgnored private let defaultAvatar: @Sendable () -> AvatarSpriteSet?
  /// The generation under way: the tests wait for it rather than for a length of time.
  @ObservationIgnored private(set) var task: Task<Void, Never>?

  public init(
    workshop: AvatarWorkshop, store: any AvatarStore,
    generators: (any AvatarGeneratorResolving)?,
    defaultAvatar: @escaping @Sendable () -> AvatarSpriteSet?
  ) {
    self.workshop = workshop
    self.store = store
    self.generators = generators
    self.defaultAvatar = defaultAvatar
  }

  // MARK: - Loading

  /// Reads the avatar kept on disk; the default one when there is none, or when it cannot be used.
  public func load() async {
    do {
      if let kept = try await store.load() {
        setCurrent(kept, isCustom: true)
        return
      }
    } catch AvatarStoreError.incomplete(let missing) {
      problem = .storedAvatar(missing: missing)
    } catch {
      problem = .storedAvatar(missing: [])
    }
    setCurrent(await loadDefault(), isCustom: false)
  }

  /// The default avatar, read off the main actor: it is an archive, decoded and checked.
  private func loadDefault() async -> AvatarSpriteSet? {
    let defaultAvatar = defaultAvatar
    return await Task.detached(priority: .utility) { defaultAvatar() }.value
  }

  /// Which agents can draw now. Asked when the screen opens.
  public func refreshOptions() async {
    guard let generators else { return }
    options = await generators.options()
    if selectedProvider == nil || !options.contains(where: { $0.id == selectedProvider }) {
      selectedProvider = options.first { $0.unavailability == nil }?.id
    }
  }

  public var selectedGenerator: (any AvatarGenerating)? {
    options.first { $0.id == selectedProvider && $0.unavailability == nil }?.generator
  }

  public var canGenerate: Bool {
    work == nil && !isImporting && selectedGenerator != nil
      && !AvatarPrompt.sanitizedDescription(description).isEmpty
  }

  // MARK: - Making

  /// Draws the whole set from the description, in the background.
  public func generate() {
    guard canGenerate, let generator = selectedGenerator, let provider = selectedProvider else {
      return
    }
    let description = description
    run(.wholeSet) { workshop in
      try await workshop.generate(
        description: description, name: "", provider: provider, with: generator)
    }
  }

  /// Draws one expression of the candidate again — or of the avatar in use, which then becomes
  /// the candidate.
  public func regenerate(_ expression: AvatarExpression) {
    guard work == nil, !isImporting, let generator = selectedGenerator,
      let base = candidate ?? (isCustom ? current : nil)
    else { return }
    run(.expression(expression)) { workshop in
      try await workshop.regenerate(expression, in: base, with: generator)
    }
  }

  /// Stops the generation under way: its process is stopped, nothing changes.
  public func cancel() {
    currentRun = nil
    task?.cancel()
    task = nil
    work = nil
  }

  private func run(
    _ kind: Work, _ body: @escaping @Sendable (AvatarWorkshop) async throws -> AvatarSpriteSet
  ) {
    problem = nil
    work = (kind, Date())
    let workshop = workshop
    let run = UUID()
    currentRun = run
    task = Task { [weak self] in
      do {
        let result = try await body(workshop)
        self?.finish(with: result, run: run)
      } catch let error as AvatarGenerationError {
        self?.fail(.generation(error), run: run)
      } catch {
        self?.fail(.generation(.failed("unexpected")), run: run)
      }
    }
  }

  /// The run whose result counts. A run cancelled, or replaced, may still end — in any way,
  /// cancelled in the middle of launching its process — and must then change nothing.
  @ObservationIgnored private var currentRun: UUID?

  private func finish(with avatar: AvatarSpriteSet, run: UUID) {
    guard currentRun == run else { return }
    currentRun = nil
    work = nil
    task = nil
    setCandidate(avatar)
    lastEvent = UUID()
    Announcer.announce(
      avatar.isComplete
        ? LocalizedStringResource(
          "The avatar is ready: check it, then use it.", bundle: .module,
          comment: "Said when a generated avatar can be previewed.")
        : LocalizedStringResource(
          "The avatar is ready, with expressions still missing.", bundle: .module,
          comment: "Said when an incomplete avatar can be previewed."))
  }

  private func fail(_ problem: Problem, run: UUID) {
    guard currentRun == run else { return }
    currentRun = nil
    work = nil
    task = nil
    self.problem = problem
    lastEvent = UUID()
    Announcer.announce(AvatarPresentation.message(for: problem))
  }

  // MARK: - Archives

  /// Reads an archive into the candidate, off the main actor: decoding its images takes time.
  /// Nothing changes in use until it is accepted, and nothing is read while a generation runs.
  public func importArchive(_ data: Data) async {
    guard work == nil, !isImporting else { return }
    problem = nil
    isImporting = true
    defer { isImporting = false }
    let workshop = workshop
    do {
      var (avatar, ignored) = try await Task.detached(priority: .userInitiated) {
        try workshop.importArchive(data)
      }.value
      if avatar.manifest.name.isEmpty {
        avatar.manifest.name = String(
          localized: LocalizedStringResource(
            "Imported avatar", bundle: .module,
            comment: "The name of an avatar read from an archive."))
      }
      ignoredFiles = ignored
      setCandidate(avatar)
      lastEvent = UUID()
    } catch let problem as AvatarProblem {
      self.problem = .archive(problem)
    } catch {
      problem = .archive(.archiveUnreadable)
    }
  }

  /// An archive being read.
  public private(set) var isImporting = false

  /// An archive refused before it was read: too large to be one.
  public func reject(_ problem: AvatarProblem) {
    self.problem = .archive(problem)
  }

  /// The archive of the avatar in use — the default one included.
  public func exportArchive(includingDescription: Bool) -> Data? {
    guard let current else { return nil }
    do {
      return try workshop.exportArchive(current, includingDescription: includingDescription)
    } catch {
      problem = .exporting
      return nil
    }
  }

  /// The name an exported archive is given.
  public var exportFileName: String {
    let name = current?.manifest.name ?? ""
    let cleaned = name.components(separatedBy: CharacterSet(charactersIn: "/:\\")).joined(
      separator: "-")
    return cleaned.isEmpty ? "Avatar" : "Avatar - \(cleaned)"
  }

  // MARK: - Deciding

  /// The candidate becomes the avatar in use, kept across launches.
  public func accept() async {
    guard let candidate, candidate.isComplete else { return }
    do {
      try await store.save(candidate)
      setCurrent(candidate, isCustom: true)
      setCandidate(nil)
      problem = nil
    } catch {
      problem = .saving
    }
  }

  public func discard() {
    cancel()
    setCandidate(nil)
    problem = nil
  }

  /// Back to the default avatar.
  public func resetToDefault() async {
    do {
      try await store.remove()
      setCurrent(await loadDefault(), isCustom: false)
      problem = nil
    } catch {
      problem = .saving
    }
  }

  // MARK: - Images

  private func setCurrent(_ avatar: AvatarSpriteSet?, isCustom: Bool) {
    current = avatar
    self.isCustom = isCustom
    currentImages = Self.images(of: avatar)
  }

  private func setCandidate(_ avatar: AvatarSpriteSet?) {
    candidate = avatar
    candidateImages = Self.images(of: avatar)
  }

  static func images(of avatar: AvatarSpriteSet?) -> [AvatarExpression: NSImage] {
    guard let avatar else { return [:] }
    var images: [AvatarExpression: NSImage] = [:]
    for (expression, data) in avatar.sprites {
      images[expression] = NSImage(data: data)
    }
    return images
  }
}
