#!/bin/zsh

# Proves an update by Sparkle on this Mac, before a release does it for everyone (#92, ADR 0033):
# two versions of this commit, signed with the team's Developer ID, a feed served from this Mac
# and generated by the same tool as the real one, and a copy of the application of its own.
#
#   Scripts/update-check.sh build                  builds 0.9.0 and 0.9.1, their archives, a key
#   Scripts/update-check.sh serve <scenario>       installs 0.9.0 afresh and serves a feed
#   Scripts/update-check.sh clean                  removes the copy, and gives Sparkle's state back
#
# Scenarios, each from a fresh 0.9.0:
#   good          0.9.1 is offered; Install and Relaunch asks about the running agents, and after
#                 Keep Running and Install the session is taken back in 0.9.1
#   bad           0.9.1 signed with another EdDSA key: Sparkle refuses it, nothing is installed
#   unstable      0.9.1 as a release candidate: not offered on Stable, offered on Unstable
#   incompatible  0.9.1 said to speak another host protocol: Keep Running is not offered
#
# The copy is isolated: its data under build/update-check/data, its own terminal host, launched
# from a folder of its own. Sparkle relaunches it through Launch Services, which passes no
# environment: its Info.plist carries `LSEnvironment` instead, so the relaunched copy is still the
# isolated one. Sparkle keeps its own state (`SULastCheckTime`, a skipped version…) in the defaults
# of `eu.hadrien.VibeManager` whatever the copy: `serve` saves those keys first, and `clean` puts
# them back as they were. Nothing of it is ever built into a release.

set -euo pipefail

readonly repository_root="${0:A:h:h}"
readonly work="$repository_root/build/update-check"
readonly port=8492
readonly feed="http://127.0.0.1:$port"
readonly installed="$work/Applications/Vibe Manager.app"
readonly old_version="0.9.0" new_version="0.9.1"
readonly domain="eu.hadrien.VibeManager"
readonly saved_state="$work/sparkle-defaults.plist"

fail() {
  print -u2 "update-check: $*"
  exit 1
}

cd "$repository_root"

team="${VIBE_TEAM_ID:-}"
for configuration in Configuration/Local.xcconfig Configuration/Shared.xcconfig; do
  [[ -z "$team" && -f "$configuration" ]] || continue
  team="$(sed -n 's/^[[:space:]]*DEVELOPMENT_TEAM[[:space:]]*=[[:space:]]*\([A-Z0-9]*\).*/\1/p' \
    "$configuration" | head -1)"
done

sparkle_tool() {
  local tool="$1"
  shift
  local tools="$repository_root/build/sparkle-2.10.0"
  if [[ ! -x "$tools/bin/$tool" ]]; then
    mkdir -p "$tools"
    curl --fail --silent --show-error --location --output "$tools.tar.xz" \
      "https://github.com/sparkle-project/Sparkle/releases/download/2.10.0/Sparkle-2.10.0.tar.xz"
    [[ "$(shasum -a 256 "$tools.tar.xz" | cut -d ' ' -f 1)" \
      == "c2bf58aa8387266ac179357b1415d6f2635f044da8be41042af32425dae6da0c" ]] \
      || fail "the Sparkle archive is not the one expected"
    tar -xf "$tools.tar.xz" -C "$tools" ./bin/sign_update
    rm -f "$tools.tar.xz"
  fi
  "$tools/bin/$tool" "$@"
}

# Sparkle's keys of the application's defaults, as they were before the first `serve`.
save_sparkle_state() {
  [[ -f "$saved_state" ]] && return
  mkdir -p "$work"
  defaults export "$domain" - 2>/dev/null | python3 -c '
import plistlib, sys
data = sys.stdin.buffer.read()
domain = plistlib.loads(data) if data.strip() else {}
kept = {key: value for key, value in domain.items() if key.startswith("SU")}
sys.stdout.buffer.write(plistlib.dumps(kept))
' > "$saved_state"
}

restore_sparkle_state() {
  [[ -f "$saved_state" ]] || return 0
  python3 - "$domain" "$saved_state" <<'PYTHON'
import datetime, plistlib, subprocess, sys
domain, saved = sys.argv[1], plistlib.load(open(sys.argv[2], "rb"))
exported = subprocess.run(["defaults", "export", domain, "-"], capture_output=True).stdout
current = plistlib.loads(exported) if exported.strip() else {}
for key in [key for key in current if key.startswith("SU")]:
    subprocess.run(["defaults", "delete", domain, key], check=True)
for key, value in saved.items():
    if isinstance(value, bool):
        typed = ["-bool", "YES" if value else "NO"]
    elif isinstance(value, int):
        typed = ["-int", str(value)]
    elif isinstance(value, float):
        typed = ["-float", repr(value)]
    elif isinstance(value, datetime.datetime):
        typed = ["-date", value.strftime("%Y-%m-%d %H:%M:%S +0000")]
    else:
        typed = ["-string", str(value)]
    subprocess.run(["defaults", "write", domain, key] + typed, check=True)
PYTHON
  rm -f "$saved_state"
  print "Sparkle's state in $domain is back as it was"
}

# A throwaway Ed25519 pair: the release key never signs a test build.
make_key() {
  cat > "$work/keys/make.swift" <<'SWIFT'
import CryptoKit
let key = Curve25519.Signing.PrivateKey()
print(key.rawRepresentation.base64EncodedString())
print(key.publicKey.rawRepresentation.base64EncodedString())
SWIFT
  local pair
  pair="$(xcrun swift "$work/keys/make.swift")"
  print -rn -- "${${(f)pair}[1]}" > "$work/keys/$1.private"
  print -rn -- "${${(f)pair}[2]}" > "$work/keys/$1.public"
}

build() {
  [[ "$team" =~ '^[A-Z0-9]{10}$' ]] || fail "no team: set VIBE_TEAM_ID or DEVELOPMENT_TEAM"
  local identity
  identity="$(security find-identity -v -p codesigning \
    | sed -n "s/.*\"\(Developer ID Application: .*($team)\)\"/\1/p" | head -1)"
  [[ -n "$identity" ]] || fail "no Developer ID Application certificate for team $team"
  local available
  available="$(df -g "$repository_root" | awk 'NR == 2 { print $4 }')"
  (( available >= 6 )) || fail "only $available GB free: a Release build needs about 6"

  rm -rf "$work/builds" "$work/keys"
  mkdir -p "$work/builds" "$work/keys"
  make_key release
  make_key other

  # The application's own Info.plist, plus local networking for the feed on this Mac and the
  # environment that keeps the copy isolated across Sparkle's relaunch.
  local plist="$work/Info.plist"
  cp App/VibeManagerApp/Info.plist "$plist"
  plutil -insert NSAppTransportSecurity -json '{"NSAllowsLocalNetworking":true}' "$plist"
  plutil -insert LSEnvironment -json \
    "{\"VIBE_DATA_DIRECTORY\":\"$work/data\",\"VIBE_UPDATES\":\"on\",\"VIBE_ENABLE_MOCK_AGENT\":\"1\"}" \
    "$plist"

  local version build_number
  for version build_number in "$old_version" 1 "$new_version" 2; do
    print "\n==> Building $version ($build_number)"
    xcodebuild \
      -project VibeManager.xcodeproj -scheme VibeManager -configuration Release \
      -destination 'generic/platform=macOS' -derivedDataPath "$work/DerivedData" \
      -skipPackagePluginValidation \
      MARKETING_VERSION="$version" CURRENT_PROJECT_VERSION="$build_number" \
      DEVELOPMENT_TEAM="$team" CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY="$identity" \
      INFOPLIST_FILE="$plist" VIBE_UPDATE_FEED_URL="$feed/appcast.xml" \
      VIBE_UPDATE_PUBLIC_KEY="$(<"$work/keys/release.public")" \
      build > "$work/build-$version.log" 2>&1 \
      || { grep -E 'error:' "$work/build-$version.log" | head -20; fail "$version did not build"; }
    local product="$work/DerivedData/Build/Products/Release/Vibe Manager.app"
    [[ "$(defaults read "$product/Contents/Info.plist" CFBundleShortVersionString)" == "$version" ]] \
      || fail "the product is not $version"
    codesign --verify --deep --strict "$product" || fail "$version does not verify"
    mkdir -p "$work/builds/$version"
    ditto "$product" "$work/builds/$version/Vibe Manager.app"
  done
  # The derived data is the bulk of the disk used, and nothing reads it again.
  rm -rf "$work/DerivedData"

  ditto -c -k --sequesterRsrc --keepParent "$work/builds/$new_version/Vibe Manager.app" \
    "$work/builds/VibeManager-$new_version.zip"
  print "\nBuilt. Next: Scripts/update-check.sh serve good"
}

serve() {
  local scenario="$1"
  [[ -d "$work/builds/$old_version" ]] || fail "nothing built: Scripts/update-check.sh build"
  local archive="$work/builds/VibeManager-$new_version.zip"
  local key="release" prerelease=false host_protocol=1
  case "$scenario" in
    good) ;;
    bad) key="other" ;;
    unstable) prerelease=true ;;
    incompatible) host_protocol=2 ;;
    *) fail "unknown scenario $scenario: good, bad, unstable or incompatible" ;;
  esac

  pgrep -f -- "$installed/Contents/MacOS/" >/dev/null \
    && fail "the test copy is running: quit it first (and its agents, with Stop All)"

  save_sparkle_state
  print "==> Installing $old_version afresh"
  rm -rf "$work/Applications" "$work/data" "$work/feed"
  mkdir -p "$work/Applications" "$work/data" "$work/feed/items"
  ditto "$work/builds/$old_version/Vibe Manager.app" "$installed"
  cp "$archive" "$work/feed/"

  print "==> Writing the feed ($scenario)"
  local signature length tag="v$new_version"
  signature="$(sparkle_tool sign_update --ed-key-file "$work/keys/$key.private" -p "$archive")"
  length="$(stat -f %z "$archive")"
  print -r -- "{\"version\":\"$new_version\",\"build\":\"2\",\"archive\":\"${archive:t}\",\"length\":$length,\"edSignature\":\"$signature\",\"minimumSystemVersion\":\"14.0\",\"hostProtocol\":$host_protocol}" \
    > "$work/feed/items/$tag.json"
  print -r -- "[{\"tag_name\":\"$tag\",\"draft\":false,\"prerelease\":$prerelease,\"html_url\":\"$feed/\",\"published_at\":\"2026-09-29T12:00:00Z\",\"body\":\"The update check of #92.\\n\\n<!-- release-checklist -->\\nNot shown.\",\"assets\":[{\"name\":\"${archive:t}\",\"size\":$length,\"browser_download_url\":\"$feed/${archive:t}\"}]}]" \
    > "$work/feed/releases.json"
  swift run --package-path Packages/ReleaseTools appcast \
    --releases "$work/feed/releases.json" --items "$work/feed/items" \
    --output "$work/feed/appcast.xml"

  cat <<STEPS

==> Serving $feed/appcast.xml — Ctrl-C when done.

In another terminal:  open "$installed"
Then, in the copy (its title bar reads $old_version in About Vibe Manager):
  1. Start a session with the mock agent; leave it running.
STEPS
  case "$scenario" in
    good) print "  2. Vibe Manager → Check for Updates…: $new_version is offered, with its notes and
     without the checklist. Install and Relaunch asks about the running agent.
  3. Keep Running and Install: $new_version opens, the session is running, its history on screen.
  4. Settings → Privacy: Full Disk Access as it was before the update." ;;
    bad) print "  2. Vibe Manager → Check for Updates…, Install: Sparkle says the update is improperly
     signed, and $old_version keeps running." ;;
    unstable) print "  2. Check for Updates…: nothing new on Stable.
  3. Settings → Updates → Channel: Unstable, then Check Now: $new_version is offered." ;;
    incompatible) print "  2. Check for Updates…, Install and Relaunch: « can't take back the running agents »,
     Later or Stop All and Install — no Keep Running. Later: nothing is installed now." ;;
  esac
  print "\nThen quit the copy (Stop All), Ctrl-C here, and Scripts/update-check.sh clean.\n"
  python3 -m http.server "$port" --bind 127.0.0.1 --directory "$work/feed"
}

case "${1:-}" in
  build) build ;;
  serve) serve "${2:-good}" ;;
  clean)
    pgrep -f -- "$installed/Contents/MacOS/" >/dev/null && fail "the test copy is running: quit it"
    rm -rf "$work/Applications" "$work/data" "$work/feed" "$work/DerivedData"
    restore_sparkle_state
    ;;
  *) fail "usage: Scripts/update-check.sh build | serve <scenario> | clean" ;;
esac
